server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS} # Kết nói với máy chủ Kafka qua cổng 9094
    producer:
      # Truyền message(key-value) dưới dạng chuỗi
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: ${SPRING_JWT_SIGNER_KEY}
  valid-duration: 2
  refreshable-duration: 4

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/