name: E-Commerce
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass admin
  kafka:
    image: "bitnamilegacy/kafka:latest"
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  mysql:
    image: mysql:8.0.36-debian
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - '8888:8888'
    environment:
      - DISCOVERY_DEFAULT_ZONE=${DISCOVERY_DEFAULT_ZONE}
    depends_on:
      - discovery-server
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    restart: always
    ports:
      - '8761:8761'
  identity-service:
    build: ./identity-service
    container_name: identity-service
    restart: always
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - SPRING_DATASOURCE_URL=${IDENTITY_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${IDENTITY_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${IDENTITY_DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
      - DISCOVERY_DEFAULT_ZONE=${DISCOVERY_DEFAULT_ZONE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - discovery-server
      - mysql
      - redis
  profile-service:
    build: ./profile-service
    container_name: profile-service
    restart: always
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=${PROFILE_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${PROFILE_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PROFILE_DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - DISCOVERY_DEFAULT_ZONE=${DISCOVERY_DEFAULT_ZONE}
    depends_on:
      - discovery-server
      - neo4j
  file-service:
    build: ./file-service
    container_name: file-service
    restart: always
    ports:
      - '8083:8083'
    environment:
      - SPRING_DATASOURCE_URL=${FILE_DB_URI}
      - SPRING_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - SPRING_CLOUD_API_KEY=${CLOUDINARY_API_KEY}
      - SPRING_CLOUD_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - discovery-server
      - mongodb
  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=${NOTIFICATION_DB_URL}
      - SPRING_BREVO_URL=${EMAIL_BREVO_URL}
      - SPRING_BREVO_API_KEY=${EMAIL_BREVO_API_KEY}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - DISCOVERY_DEFAULT_ZONE=${DISCOVERY_DEFAULT_ZONE}
    depends_on:
      - discovery-server
      - kafka
      - mongodb