CREATE DATABASE inventory_service_db;
CREATE DATABASE catalog_service_db;
CREATE DATABASE payment_service_db;
CREATE DATABASE shipment_service_db;
CREATE DATABASE order_service_db;

\c inventory_service_db;
CREATE SEQUENCE IF NOT EXISTS warehouse_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS inventories_seq START WITH 1 INCREMENT BY 1;

\c catalog_service_db;
CREATE SEQUENCE IF NOT EXISTS attributer_value_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS attributer_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS brand_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS category_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS product_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS media_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS variant_seq START WITH 1 INCREMENT BY 1;

\c shipment_service_db;
CREATE SEQUENCE IF NOT EXISTS user_address_seq START WITH 1 INCREMENT BY 1;