server:
  port: 8088
  servlet:
    context-path: /shipment

spring:
  application:
    name: shipment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          json_format_mapper: jackson
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS} # Kết nói với máy chủ Kafka qua cổng 9094
    producer:
      # Truyền message(key-value) dưới dạng chuỗi
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: shipment-group-v1  #Tên nhóm của consumer
      auto-offset-reset: earliest #Nếu group-id này chưa từng đọc message trong topic thì đọc từ message cũ nhất
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" #Vô hiệu hóa cơ chế bảo mật
app:
  ghn:
    api:
      token: ${SPRING_GHN_API_TOKEN}
      shop-id: ${SPRING_GHN_SHOP_ID}
      base-url: ${SPRING_GHN_BASE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_DEFAULT_ZONE}